name:  Example CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          [ ! -f "requirements.txt" ] || pip install -r requirements.txt

      - name: list python packages
        run: pip list

      - name: execute inference script
        env:
          COMET_API_KEY: ${{ secrets.COMET_API_KEY }}
          COMET_MPM: ${{ secrets.COMET_MPM }}
        run: python inference.py
